# Use the § symbol for color coding
# Use %name for the name of the player who did /vanish
#   Default Config:
#     FakeLeave-message: "§e%name Left the game"
#     FakeJoin-message: "§e%name joined the game"

# The message that will be sent to online players when you will activate your vanish
enable-leave: true
FakeLeave-message: "§e%name left the game"

# The message that will be sent to online players when you will deactivate you vanish
enable-join: true
FakeJoin-message: "§e%name joined the game"
...
